apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: my-fastapi-stack
type: Opaque
# 使用 stringData 字段，键和值都使用明文
stringData:
  # Key: 保持人类可读，并且符合命名规范（字母、数字、下划线、连字符、点）
  POSTGRES_USER: "ziran"

  # Value: 直接写明文密码
  POSTGRES_PASSWORD: "123456"

---
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: my-fastapi-stack
type: Opaque
stringData:
  # Key
  JWT_SECRET_KEY: "your_super_secret_for_jwt"